# Training example

This notebook shows how to train neural network in python in a way that is compatible with the C library.
It does not shows how to solve any specific problem, but rather how to transfer data to C.

In [1]:
import numpy as np

In [2]:
# this neural network works the same way as the one in C

class NeuralNetwork:
    def __init__(self, shape: np.array, genotype: np.array):
        self.activation = np.tanh
        self.w = []
        self.genotype = genotype


        parameters_n = 0
        for i in range(len(shape) - 1):
            parameters_n += shape[i] * shape[i+1]
            parameters_n += shape[i+1]

        assert len(self.genotype) == parameters_n, f"genotype: {len(self.genotype)}, parameters: {parameters_n}"
            
        for i in range(len(shape) - 1):
            self.w.append(genotype[:shape[i] * shape[i+1]].reshape(shape[i + 1], shape[i]))
            genotype = genotype[shape[i] * shape[i+1]:]

            self.w.append(genotype[:shape[i+1]])
            self.w[-1] = self.w[-1].reshape(shape[i+1], 1)
            genotype = genotype[shape[i+1]:]

        
    def forward(self, inputs):
        inputs = inputs.reshape(1, -1).T
        for i in range(0, len(self.w), 2):
            inputs = self.w[i] @ inputs
            inputs += self.w[i + 1]
            inputs = self.activation(inputs)
        
        return inputs

In [6]:
# Let's say we want to solve some problem by implementing genetic algorithm.
# It is done by finding the best "genotype" of the function.
# In this case, our function is neural network.

# Create a random genotype
genotype = np.random.randn(170)

# Create a nn with that genotype
nn = NeuralNetwork(np.array([10, 8, 6, 4]), genotype)

# In case you are wondering how do I know that the genotype has to have 26 elements:
# neural network class checks if genotype can fill all weights and biases and tells you if there is wrong number of elements.

# If neural network with that genotype is doing well, you can print the genotype and paste it into the C code.
print(repr(genotype))

# Of course, this genotype will not be good, because it was generated randomly.
# You will have to implement some sort of learning algorithm.

array([-3.31838594e-01, -2.23762525e-02,  2.73940038e-01, -1.31142089e+00,
       -1.36656624e-01,  1.77825490e+00,  7.38141880e-01, -2.30594706e-01,
       -1.61741720e-01, -2.06439010e-01,  1.35745543e+00,  2.27763591e-01,
       -3.07974636e-01, -3.67069730e-01, -2.78982922e-01,  1.48692628e+00,
       -1.35086311e+00,  3.40995063e-01, -1.79470510e-01, -9.39800359e-01,
       -1.22211747e+00, -6.19336711e-01, -2.13400729e-01, -2.14624437e-01,
       -1.06482397e+00,  1.05590913e-03, -9.58332082e-01,  1.88470809e-02,
        6.20301902e-01,  2.00752341e-01,  1.62676132e+00,  1.69156594e+00,
       -4.29060510e-01, -1.26836783e+00, -1.48037855e+00,  5.63941690e-01,
       -7.55071026e-01,  4.43811386e-01, -3.81510892e-01,  5.37289734e-01,
       -1.12965330e+00, -3.23319564e-01, -1.93101741e-02,  3.32779290e-01,
       -3.79760161e-01,  3.10542120e-01, -8.53541341e-01,  1.43096820e+00,
       -1.37408806e+00,  3.92361719e-01, -1.61662605e+00, -5.99159714e-02,
        1.48375248e-01,  

In [8]:
inputs = np.random.randn(10)
print(repr(inputs))
print(nn.forward(inputs))

array([-1.07345792,  0.27974646,  2.58024343,  0.25565184,  0.15403624,
       -1.38389756,  0.32025532, -0.07782008,  0.23977592, -1.03075154])
[[-0.93278648]
 [-0.49551506]
 [-0.99986985]
 [-0.19258657]]
